### ISSUE TITLE
Usulan: Koneksi ke PostGIS

### ISSUE THREAD

**Issue by firmanhadi** [andyprasetya/webmap-development-server#1]
Terima kasih telah menjelaskan tahapan pembuatan webgis yang demikian lengkap, Pak.
Khusus untuk tahapan no. 8 dari Part 4-PostGIS, apakah hal yang sama dapat dilakukan dengan menggunakan Tool DB Manager di QGIS, Pak?
Terima kasih.

Salam,

Firman.

**Comment by andyprasetya** [comment]
Wow, langsung create issue. Siiip, Pak Firman!

Saya pakai Quantum GIS versi 3.6.1 (Noosa). Nah, connection entries dalam DB Manager biasanya harus didahului dengan pembuatan connection entries pada Data Source manager. Jadi kalau kita tidak meng-create-nya dulu di Data Source Manager, ya nggak akan muncul di DB Manager. Pendeknya, DB Manager adalah "shortcut" dari connection entries yang sudah kita create pada Data Source Manager.

Dan dalam tutorial ini, saya menggunakan Data Source Manager saja, supaya pembaca lebih memahami proses creating connection-nya. (The hard-way-nya. :)) )
